modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/bernie-g/geckolib/issues"
license="MIT"
[[mods]]
modId="geckolib3"
version="${file.jarVersion}" 
displayName="GeckoLib"
displayURL="http://geckolib.com/"
logoFile="geckolib.png" 
credits="Gecko, Eliot, AzureDoom, DerToaster, Tslat"
authors="Gecko, Eliot, AzureDoom, Chappie, DerToaster, Tslat"
description='''
GeckoLib is an animation engine for Minecraft Mods, with support for complex 3D keyframe-based animations, 30+ easings, concurrent animation support, sound and particle keyframes, event keyframes, and more.
'''
[[dependencies.geckolib3]]
    modId="forge"
    mandatory=true 
    versionRange="[43.1.25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.geckolib3]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20)"
    ordering="NONE"
    side="BOTH"
